// Comprehensive list of universities and research institutions
// Organized by category for India, then international

// ─── IITs ────────────────────────────────────────────────
const IITs = [
  "IIT Madras",
  "IIT Bombay",
  "IIT Delhi",
  "IIT Kanpur",
  "IIT Kharagpur",
  "IIT Roorkee",
  "IIT Guwahati",
  "IIT Hyderabad",
  "IIT Indore",
  "IIT (BHU) Varanasi",
  "IIT Bhubaneswar",
  "IIT Gandhinagar",
  "IIT Jodhpur",
  "IIT Patna",
  "IIT Ropar",
  "IIT Mandi",
  "IIT Tirupati",
  "IIT Palakkad",
  "IIT Dharwad",
  "IIT Bhilai",
  "IIT Goa",
  "IIT Jammu",
  "IIT Dhanbad (ISM)",
]

// ─── NITs ────────────────────────────────────────────────
const NITs = [
  "NIT Trichy",
  "NIT Surathkal (NITK)",
  "NIT Warangal",
  "NIT Calicut",
  "NIT Rourkela",
  "NIT Durgapur",
  "NIT Kurukshetra",
  "NIT Allahabad (MNNIT)",
  "NIT Jamshedpur",
  "NIT Surat (SVNIT)",
  "NIT Nagpur (VNIT)",
  "NIT Srinagar",
  "NIT Silchar",
  "NIT Hamirpur",
  "NIT Jalandhar",
  "NIT Raipur",
  "NIT Agartala",
  "NIT Jaipur (MNIT)",
  "NIT Patna",
  "NIT Bhopal (MANIT)",
  "NIT Meghalaya",
  "NIT Manipur",
  "NIT Mizoram",
  "NIT Nagaland",
  "NIT Sikkim",
  "NIT Arunachal Pradesh",
  "NIT Uttarakhand",
  "NIT Delhi",
  "NIT Goa",
  "NIT Puducherry",
  "NIT Andhra Pradesh",
]

// ─── IISERs ─────────────────────────────────────────────
const IISERs = [
  "IISER Pune",
  "IISER Kolkata",
  "IISER Mohali",
  "IISER Bhopal",
  "IISER Thiruvananthapuram",
  "IISER Tirupati",
  "IISER Berhampur",
]

// ─── Central Universities ────────────────────────────────
const CENTRAL_UNIVERSITIES = [
  "University of Delhi",
  "Jawaharlal Nehru University (JNU)",
  "Banaras Hindu University (BHU)",
  "University of Hyderabad",
  "Aligarh Muslim University (AMU)",
  "Jamia Millia Islamia",
  "Visva-Bharati University",
  "Pondicherry University",
  "University of Allahabad",
  "Tezpur University",
  "Assam University",
  "Nagaland University",
  "Manipur University",
  "Mizoram University",
  "Tripura University",
  "Sikkim University",
  "Rajiv Gandhi University",
  "Central University of Tamil Nadu",
  "Central University of Kerala",
  "Central University of Karnataka",
  "Central University of Rajasthan",
  "Central University of Punjab",
  "Central University of Haryana",
  "Central University of Jharkhand",
  "Central University of Gujarat",
  "Central University of Kashmir",
  "Central University of Himachal Pradesh",
  "Central University of Odisha",
  "Central University of South Bihar",
  "Mahatma Gandhi Central University",
  "Hemvati Nandan Bahuguna Garhwal University",
  "Babasaheb Bhimrao Ambedkar University",
  "Indira Gandhi National Open University (IGNOU)",
  "Maulana Azad National Urdu University",
]

// ─── Major State Universities ────────────────────────────
const STATE_UNIVERSITIES = [
  // Tamil Nadu
  "Anna University, Chennai",
  "University of Madras",
  "Bharathiar University",
  "Bharathidasan University",
  "Madurai Kamaraj University",
  "Alagappa University",
  "Manonmaniam Sundaranar University",
  "Periyar University",
  "Thiruvalluvar University",
  "Tamil Nadu Open University",
  "Mother Teresa Women's University",
  "Annamalai University",
  // Kerala
  "University of Kerala",
  "Cochin University of Science and Technology (CUSAT)",
  "Calicut University",
  "Mahatma Gandhi University, Kottayam",
  "Kannur University",
  // Karnataka
  "Bangalore University",
  "University of Mysore",
  "Mangalore University",
  "Karnatak University, Dharwad",
  "Gulbarga University",
  "Visvesvaraya Technological University (VTU)",
  "Kuvempu University",
  "Davangere University",
  // Andhra Pradesh & Telangana
  "Osmania University",
  "Andhra University",
  "Sri Venkateswara University",
  "Acharya Nagarjuna University",
  "Kakatiya University",
  "JNTU Hyderabad",
  "JNTU Kakinada",
  "JNTU Anantapur",
  "University of Hyderabad",
  // Maharashtra
  "University of Mumbai",
  "Savitribai Phule Pune University",
  "Shivaji University, Kolhapur",
  "Rashtrasant Tukadoji Maharaj Nagpur University",
  "Dr. Babasaheb Ambedkar Marathwada University",
  "North Maharashtra University",
  // West Bengal
  "Jadavpur University",
  "University of Calcutta",
  "Presidency University, Kolkata",
  "University of Burdwan",
  "University of Kalyani",
  "University of North Bengal",
  // Gujarat
  "Gujarat University",
  "Maharaja Sayajirao University of Baroda",
  "Sardar Patel University",
  "Saurashtra University",
  // Rajasthan
  "University of Rajasthan",
  "Maharshi Dayanand Saraswati University",
  "Jai Narain Vyas University",
  "Mohanlal Sukhadia University",
  // Madhya Pradesh
  "Devi Ahilya Vishwavidyalaya",
  "Rani Durgavati Vishwavidyalaya",
  "Barkatullah University",
  "Jiwaji University",
  // Punjab & Haryana
  "Panjab University, Chandigarh",
  "Guru Nanak Dev University",
  "Punjabi University, Patiala",
  "Kurukshetra University",
  "Maharshi Dayanand University, Rohtak",
  // Bihar & Jharkhand
  "Patna University",
  "Ranchi University",
  "Lalit Narayan Mithila University",
  "Magadh University",
  // Uttar Pradesh
  "Lucknow University",
  "Allahabad University",
  "Gorakhpur University",
  "Bundelkhand University",
  // Odisha
  "Utkal University",
  "Berhampur University",
  "Sambalpur University",
  // Northeast
  "Gauhati University",
  "Dibrugarh University",
  "North-Eastern Hill University (NEHU)",
]

// ─── Private/Deemed Universities ─────────────────────────
const PRIVATE_UNIVERSITIES = [
  "BITS Pilani",
  "BITS Pilani - Goa Campus",
  "BITS Pilani - Hyderabad Campus",
  "VIT Vellore",
  "VIT Chennai",
  "VIT Bhopal",
  "SRM Institute of Science and Technology",
  "SRM University AP",
  "Amrita Vishwa Vidyapeetham",
  "Manipal Academy of Higher Education",
  "SASTRA Deemed University",
  "Shanmugha Arts, Science, Technology & Research Academy",
  "PSG College of Technology",
  "Kumaraguru College of Technology",
  "Sri Sivasubramaniya Nadar College of Engineering",
  "Kalasalingam Academy of Research and Education",
  "Karunya Institute of Technology and Sciences",
  "Sathyabama Institute of Science and Technology",
  "Saveetha Institute of Medical and Technical Sciences",
  "Vel Tech Rangarajan Dr. Sagunthala R&D Institute",
  "Hindustan Institute of Technology and Science",
  "St. Joseph's College of Engineering",
  "Mepco Schlenk Engineering College",
  "Thiagarajar College of Engineering",
  "Government College of Technology, Coimbatore",
  "Kongu Engineering College",
  "Coimbatore Institute of Technology",
  "Bannari Amman Institute of Technology",
  "Sri Krishna College of Engineering and Technology",
  "Lovely Professional University",
  "Amity University",
  "Shiv Nadar University",
  "Ashoka University",
  "FLAME University",
  "OP Jindal Global University",
  "Symbiosis International University",
  "Christ University, Bangalore",
  "Thapar Institute of Engineering and Technology",
  "Delhi Technological University (DTU)",
  "Netaji Subhas University of Technology (NSUT)",
  "IIIT Hyderabad",
  "IIIT Delhi",
  "IIIT Bangalore",
  "IIIT Allahabad",
  "Jamia Hamdard",
  "Bharati Vidyapeeth",
  "MIT World Peace University, Pune",
  "Nirma University",
  "Dhirubhai Ambani Institute (DA-IICT)",
  "NMIMS Mumbai",
  "St. Xavier's College, Mumbai",
  "Fergusson College, Pune",
  "Loyola College, Chennai",
  "Presidency College, Chennai",
  "Madras Christian College",
  "Women's Christian College, Chennai",
  "Ethiraj College for Women",
  "Stella Maris College, Chennai",
  "Bishop Heber College, Trichy",
  "St. Joseph's College, Trichy",
  "American College, Madurai",
  "The Gandhigram Rural Institute",
  "Aarupadai Veedu Institute of Technology",
  "Velalar College of Engineering and Technology",
  "KPR Institute of Engineering and Technology",
  "Karpagam Academy of Higher Education",
  "Rajalakshmi Engineering College",
  "Sri Sairam Engineering College",
  "RMK Engineering College",
  "Easwari Engineering College",
  "Meenakshi Sundararajan Engineering College",
]

// ─── Research Labs & Institutes ──────────────────────────
const RESEARCH_INSTITUTES = [
  "IISc Bangalore",
  "CSIR-CECRI Karaikudi",
  "CSIR-NCL Pune",
  "CSIR-CGCRI Kolkata",
  "CSIR-NIIST Thiruvananthapuram",
  "CSIR-NPL New Delhi",
  "CSIR-NML Jamshedpur",
  "CSIR-IICT Hyderabad",
  "CSIR-CLRI Chennai",
  "CSIR-CSMCRI Bhavnagar",
  "ARCI Hyderabad",
  "JNCASR Bangalore",
  "ICT Mumbai",
  "INST Mohali",
  "Institute of Nano Science and Technology",
  "Raman Research Institute",
  "Indian Association for the Cultivation of Science (IACS)",
  "Saha Institute of Nuclear Physics",
  "S.N. Bose National Centre for Basic Sciences",
  "Bhabha Atomic Research Centre (BARC)",
  "Indira Gandhi Centre for Atomic Research (IGCAR)",
  "Defence Metallurgical Research Laboratory (DMRL)",
  "Central Electrochemical Research Institute (CECRI)",
  "National Aerospace Laboratories (NAL)",
  "Vikram Sarabhai Space Centre (VSSC)",
  "Indian Institute of Petroleum, Dehradun",
  "Centre for Materials for Electronics Technology (C-MET)",
  "International Advanced Research Centre for Powder Metallurgy (ARCI)",
  "Raja Ramanna Centre for Advanced Technology (RRCAT)",
  "Inter-University Accelerator Centre (IUAC)",
  "Harish-Chandra Research Institute",
  "Physical Research Laboratory, Ahmedabad",
  "National Chemical Laboratory (NCL)",
  "Indian Institute of Chemical Biology",
  "Tata Institute of Fundamental Research (TIFR)",
  "Chennai Mathematical Institute",
  "Institute of Mathematical Sciences, Chennai",
]

// ─── International Universities ──────────────────────────
const INTERNATIONAL_UNIVERSITIES = [
  // United States
  "MIT (Massachusetts Institute of Technology)",
  "Stanford University",
  "Caltech (California Institute of Technology)",
  "Harvard University",
  "UC Berkeley",
  "University of Michigan",
  "Georgia Institute of Technology",
  "University of Illinois Urbana-Champaign",
  "University of Texas at Austin",
  "Penn State University",
  "Cornell University",
  "Princeton University",
  "Yale University",
  "Columbia University",
  "University of Chicago",
  "Northwestern University",
  "University of Wisconsin-Madison",
  "Purdue University",
  "University of Minnesota",
  "Ohio State University",
  "Carnegie Mellon University",
  "University of Washington",
  "UCLA",
  "UC San Diego",
  "UC Santa Barbara",
  "UC Davis",
  "University of Florida",
  "University of Maryland",
  "University of Colorado Boulder",
  "Virginia Tech",
  "Argonne National Laboratory",
  "Brookhaven National Laboratory",
  "Lawrence Berkeley National Laboratory",
  "Oak Ridge National Laboratory",
  "Pacific Northwest National Laboratory",
  "Sandia National Laboratories",
  "National Renewable Energy Laboratory (NREL)",
  // United Kingdom
  "University of Oxford",
  "University of Cambridge",
  "Imperial College London",
  "University College London (UCL)",
  "University of Manchester",
  "University of Edinburgh",
  "University of Southampton",
  "University of Bath",
  "University of Warwick",
  "University of Sheffield",
  "University of Birmingham",
  "University of Bristol",
  "University of Leeds",
  "University of Nottingham",
  "University of Glasgow",
  "University of St Andrews",
  "Queen Mary University of London",
  // Germany
  "Technical University of Munich (TUM)",
  "RWTH Aachen University",
  "Max Planck Institute",
  "Helmholtz Centre",
  "Karlsruhe Institute of Technology (KIT)",
  "University of Stuttgart",
  "TU Berlin",
  "LMU Munich",
  "University of Göttingen",
  "Forschungszentrum Jülich",
  "Fraunhofer Institute",
  // France
  "Sorbonne University",
  "École Polytechnique",
  "CNRS (Centre National de la Recherche Scientifique)",
  "CEA (Commissariat à l'énergie atomique)",
  "Université Paris-Saclay",
  "Université Grenoble Alpes",
  // China
  "Tsinghua University",
  "Peking University",
  "Chinese Academy of Sciences",
  "Fudan University",
  "Zhejiang University",
  "University of Science and Technology of China",
  "Nanjing University",
  "Shanghai Jiao Tong University",
  "Wuhan University",
  "Xiamen University",
  "Tianjin University",
  "Harbin Institute of Technology",
  "Dalian University of Technology",
  "South China University of Technology",
  "Sun Yat-sen University",
  // Japan
  "University of Tokyo",
  "Kyoto University",
  "Osaka University",
  "Tohoku University",
  "Tokyo Institute of Technology",
  "Nagoya University",
  "NIMS (National Institute for Materials Science)",
  "AIST (Advanced Industrial Science and Technology)",
  // South Korea
  "KAIST",
  "Seoul National University",
  "POSTECH",
  "Korea University",
  "Yonsei University",
  "Hanyang University",
  "Sungkyunkwan University",
  "Korea Institute of Science and Technology (KIST)",
  "Korea Electrotechnology Research Institute (KERI)",
  // Canada
  "University of Toronto",
  "University of Waterloo",
  "McGill University",
  "University of British Columbia",
  "Dalhousie University",
  "McMaster University",
  "University of Alberta",
  "Western University",
  // Australia
  "University of Melbourne",
  "University of New South Wales",
  "University of Sydney",
  "Monash University",
  "University of Queensland",
  "Australian National University",
  "Deakin University",
  "University of Wollongong",
  // Singapore
  "National University of Singapore",
  "Nanyang Technological University",
  // Switzerland
  "ETH Zurich",
  "EPFL (École Polytechnique Fédérale de Lausanne)",
  "Paul Scherrer Institute",
  "University of Zurich",
  "University of Bern",
  // Others
  "Technion – Israel Institute of Technology",
  "Hebrew University of Jerusalem",
  "Weizmann Institute of Science",
  "National Taiwan University",
  "KTH Royal Institute of Technology, Sweden",
  "Chalmers University of Technology, Sweden",
  "Uppsala University, Sweden",
  "TU Delft, Netherlands",
  "Eindhoven University of Technology, Netherlands",
  "University of Twente, Netherlands",
  "Politecnico di Milano, Italy",
  "University of Bologna, Italy",
  "Universitat de Barcelona, Spain",
  "Universidade de São Paulo, Brazil",
  "UNICAMP, Brazil",
]

// ─── Export combined list ────────────────────────────────
export const INSTITUTIONS = [
  ...IITs,
  ...NITs,
  ...IISERs,
  ...CENTRAL_UNIVERSITIES,
  ...STATE_UNIVERSITIES,
  ...PRIVATE_UNIVERSITIES,
  ...RESEARCH_INSTITUTES,
  ...INTERNATIONAL_UNIVERSITIES,
  "Other",
]

// Export categorized for potential use
export const INSTITUTION_CATEGORIES = {
  "IITs": IITs,
  "NITs": NITs,
  "IISERs": IISERs,
  "Central Universities": CENTRAL_UNIVERSITIES,
  "State Universities": STATE_UNIVERSITIES,
  "Private & Deemed Universities": PRIVATE_UNIVERSITIES,
  "Research Institutes & Labs": RESEARCH_INSTITUTES,
  "International Universities": INTERNATIONAL_UNIVERSITIES,
}
